name: Node CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Install dependencies
      run: yarn install
      
    - name: Build
      run: yarn vuepress build
      
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3.9.0
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./.vuepress/dist
